### ISSUE TITLE
Feature request: `did-enter-viewport` and `did-exit-viewport` element modifiers

### ISSUE THREAD

**Issue by gmurphey** [DockYard/ember-in-viewport#177]
Would be awesome to be able to do things like:

```
<div
  {{did-enter-viewport enterCallback}}
  {{did-exit-viewport exitCallback}}
>
  Foo
</div>
```

Where `enterCallback` and `exitCallback` are functions or actions that receive the `element` as a parameter.

**Comment by snewcomer** [comment]
Interesting idea and thx for putting up an issue.  So you are referring to this RFC I'm guessing? https://github.com/emberjs/rfcs/pull/353/files

Since these functions are called once I believe, what exactly would these modifiers do?  What happens when they elements they are bound to are not in viewport, but are still only called once (ie. not watchign the DOM)

**Comment by snewcomer** [comment]
@gmurphey Is this something you would want to work on?  Otherwise, I'll see about getting it done on our side!

**Comment by snewcomer** [comment]
I'm starting work on this.  There is quite a bit to do, including ensuring we have a shared cache that can be referenced across boundaries (mixin / modifier)

**Comment by snewcomer** [comment]
@gmurphy #179. Seems pretty simple and would require installing https://github.com/emberjs/ember-render-modifiers and using the ‘did-insert’ hook.  What do you think?
